# define the initial positions of each robot in NWU frame
# change the initial rotation matrix to [1, 0, 0, 0, 1, 0, 0, 0, 1] for initialing the 
# drones right side up.
robot_1:
  position: [2, 2, -2]
  velocity: [0, 0, 0]
  rotation: [1, 0, 0, 0, -0.9995, -0.0314, 0, 0.0314, -0.9995]
  omega: [0, 0, 0]

robot_2:
  position: [-2, -2, -2]
  velocity: [0, 0, 0]
  rotation: [1, 0, 0, 0, -0.9995, -0.0314, 0, 0.0314, -0.9995]
  omega: [0, 0, 0]

robot_3:
  position: [-1, 1, -2]
  velocity: [0, 0, 0]
  rotation: [1, 0, 0, 0, -0.9995, -0.0314, 0, 0.0314, -0.9995]
  omega: [0, 0, 0]

robot_4:
  position: [1, -1, -2]
  velocity: [0, 0, 0]
  rotation: [1, 0, 0, 0, -0.9995, -0.0314, 0, 0.0314, -0.9995]
  omega: [0, 0, 0]

robot_5:
  position: [0, 0, -2]
  velocity: [0, 0, 0]
  rotation: [1, 0, 0, 0, -0.9995, -0.0314, 0, 0.0314, -0.9995]
  omega: [0, 0, 0]