# define the initial positions of each robot in NWU frame
# change the initial rotation matrix to [1, 0, 0, 0, 1, 0, 0, 0, 1] for initialing the 
# drones right side up.
robot_0:
  ros__parameters:
    position: [2.0, 2.0, -2.0]
    velocity: [0.0, 0.0, 0.0]
    rotation: [1.0, 0.0, 0.0, 0.0, -0.9995, -0.0314, 0.0, 0.0314, -0.9995]
    omega: [0.0, 0.0, 0.0]
